version: '3'
services:

  qm1:
    image: ibmcom/mq:latest
    ports:
      - "1414:1414"
      - "9443:9443"
    hostname: qm1
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_DEV=false
      - MQ_APP_PASSWORD=passw0rd
    container_name: qm1
    volumes:
      - ./etc/qm1/config.mqsc:/etc/mqm/config.mqsc
      - ./etc/qm1/mq.htpasswd:/etc/mqm/mq.htpasswd
      - ./etc/qm1/qm-service-component.ini:/etc/mqm/qm-service-component.ini
    stdin_open: true
    tty: true
    restart: always

  qm2:
    image: ibmcom/mq:latest
    ports:
      - "1415:1414"
      - "9444:9443"
    hostname: qm2
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM2
      - MQ_DEV=false
      - MQ_APP_PASSWORD=passw0rd
    container_name: qm2
    volumes:
      - ./etc/qm2/config.mqsc:/etc/mqm/config.mqsc
      - ./etc/qm2/mq.htpasswd:/etc/mqm/mq.htpasswd
      - ./etc/qm2/qm-service-component.ini:/etc/mqm/qm-service-component.ini
    stdin_open: true
    tty: true
    restart: always

  # janus:
  #   container_name: janus
  #   image: quay.io/hellofresh/janus
  #   ports:
  #     - "8080:8080"
  #     - "8081:8081"
  #   volumes:
  #     - ./etc/janus/janus.toml:/etc/janus/janus.toml
  #     - ./etc/janus/apis:/etc/janus/apis
  #
  # logio:
  #   image: geniousphp/logio
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock
  #   ports:
  #     - "28778:28778"
  #   privileged: true
  #   environment: #All these env variables are optionals
  #     - PORT=28778
  #     - DOCKER_SOCKET=/tmp/docker.sock
  #     - SHOW_LOG_BY_LABEL=logio
